### ISSUE TITLE
ERRO ENCONTRADO

### ISSUE THREAD

**Issue by evssousa** [gloriamariap/projeto-1-treinando-a-criacao-de-classes#1]
```
node Product.js
/home/runner/aulas/projeto-1-treinando-a-criacao-de-classes-main/Product.js:14
             Valor do produto: R$${this.price.tofixed(2)}
                                              ^

TypeError: this.price.tofixed is not a function
    at Product.addToStock (/home/runner/aulas/projeto-1-treinando-a-criacao-de-classes-main/Product.js:14:47)
    at Object.<anonymous> (/home/runner/aulas/projeto-1-treinando-a-criacao-de-classes-main/Product.js:30:10)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.2
```

**Comment by gloriamariap** [comment]
ATUALIZADO!

**Comment by gloriamariap** [comment]
ATUALIZADO!

**Comment by gloriamariap** [comment]
ATUALIZADO!
